# Project 9: Web Scraping, APIs & Wrappers (US Stocks)

## Web Scraping - the Dow Jones Constituents

In [1]:
import pandas as pd

In [2]:
pd.read_html("https://en.wikipedia.org/wiki/Dow_Jones_Industrial_Average")

[                                                   0  \
 0  Historical logarithmic graph of the DJIA from ...
 1                                         Foundation
 2                                           Operator
 3                                          Exchanges
 4                                     Trading symbol
 5                                       Constituents
 6                                               Type
 7                                         Market cap
 8                                   Weighting method
 9                                            Website

                                                    1
 0  Historical logarithmic graph of the DJIA from ...
 1  February 16, 1885; 135 years ago[1]May 26, 189...
 2                              S&P Dow Jones Indices
 3                      New York Stock ExchangeNASDAQ
 4                                               ^DJI
 5                                                 30
 6                                          Large cap
 7                      $8.33 trillion (Dec. 2019)[3]
 8                               Price-weighted index
 9  us.spindices.com/indices/equity/dow-jones-indu...  ,
                      Company Exchange     Symbol  \
 0                         3M     NYSE  NYSE: MMM
 1           American Express     NYSE  NYSE: AXP
 2                 Apple Inc.   NASDAQ       AAPL
 3                     Boeing     NYSE   NYSE: BA
 4           Caterpillar Inc.     NYSE  NYSE: CAT
 5        Chevron Corporation     NYSE  NYSE: CVX
 6              Cisco Systems   NASDAQ       CSCO
 7      The Coca-Cola Company     NYSE   NYSE: KO
 8                   Dow Inc.     NYSE  NYSE: DOW
 9                 ExxonMobil     NYSE  NYSE: XOM
 10             Goldman Sachs     NYSE   NYSE: GS
 11            The Home Depot     NYSE   NYSE: HD
 12                       IBM     NYSE  NYSE: IBM
 13                     Intel   NASDAQ       INTC
 14         Johnson & Johnson     NYSE  NYSE: JNJ
 15            JPMorgan Chase     NYSE  NYSE: JPM
 16                McDonald's     NYSE  NYSE: MCD
 17               Merck & Co.     NYSE  NYSE: MRK
 18                 Microsoft   NASDAQ       MSFT
 19                      Nike     NYSE  NYSE: NKE
 20                    Pfizer     NYSE  NYSE: PFE
 21          Procter & Gamble     NYSE   NYSE: PG
 22     Raytheon Technologies     NYSE  NYSE: RTX
 23   The Travelers Companies     NYSE  NYSE: TRV
 24        UnitedHealth Group     NYSE  NYSE: UNH
 25                   Verizon     NYSE   NYSE: VZ
 26                 Visa Inc.     NYSE    NYSE: V
 27                   Walmart     NYSE  NYSE: WMT
 28  Walgreens Boots Alliance   NASDAQ        WBA
 29   The Walt Disney Company     NYSE  NYSE: DIS

                           Industry  Date Added  \
 0                     Conglomerate  1976-08-09
 1               Financial services  1982-08-30
 2           Information technology  2015-03-19
 3            Aerospace and defense  1987-03-12
 4          Construction and Mining  1991-05-06
 5               Petroleum industry  2008-02-19
 6           Information technology  2009-06-08
 7                    Food industry  1987-03-12
 8                Chemical industry  2019-04-02
 9               Petroleum industry  1928-10-01
 10              Financial services  2013-09-20
 11                       Retailing  1999-11-01
 12          Information technology  1979-06-29
 13          Information technology  1999-11-01
 14         Pharmaceutical industry  1997-03-17
 15              Financial services  1991-05-06
 16                   Food industry  1985-10-30
 17         Pharmaceutical industry  1979-06-29
 18          Information technology  1999-11-01
 19                         Apparel  2013-09-20
 20         Pharmaceutical industry  2004-04-08
 21      Fast-moving consumer goods  1932-05-26
 22           Aerospace and defense  1939-03-14
 23              Financial services  2009-06-08
 24             Managed health care  2012-09-24
 25               Telecommunication  2004-04-08
 26              Financial services  2013-09-20
 27                       Retailing  1997-03-17
 28                       Retailing  2018-06-26
 29  Broadcasting and entertainment  1991-05-06

                                                 Notes  \
 0               as Minnesota Mining and Manufacturing
 1                                                 NaN
 2                                                 NaN
 3                                                 NaN
 4                                                 NaN
 5                       also 1930-07-18 to 1999-11-01
 6                                                 NaN
 7                       also 1932-05-26 to 1935-11-20
 8                                                 NaN
 9                       as Standard Oil of New Jersey
 10                                                NaN
 11                                                NaN
 12                      also 1932-05-26 to 1939-03-04
 13                                                NaN
 14                                                NaN
 15                                                NaN
 16                                                NaN
 17                                                NaN
 18                                                NaN
 19                                                NaN
 20                                                NaN
 21                                                NaN
 22  as United Aircraft, later transformed into Uni...
 23                                                NaN
 24                                                NaN
 25                                                NaN
 26                                                NaN
 27                                                NaN
 28                                                NaN
 29                                                NaN

    Index Weighting (Apr 30, 2020)
 0                           4.35%
 1                           2.68%
 2                           8.01%
 3                           3.87%
 4                           3.34%
 5                           2.63%
 6                           1.21%
 7                           1.31%
 8                           1.04%
 9                           1.32%
 10                          5.29%
 11                          6.17%
 12                          3.58%
 13                          1.72%
 14                          4.18%
 15                          2.72%
 16                          5.23%
 17                          2.25%
 18                          4.94%
 19                          2.45%
 20                          1.06%
 21                          3.26%
 22                          1.89%
 23                          2.95%
 24                          8.01%
 25                          1.62%
 26                          5.06%
 27                          3.44%
 28                          1.26%
 29                          3.12%  ,
      Year  Closing level Change in Indexin Points Change in Indexin %
 0    1885          39.29                    10.83               38.05
 1    1886          41.03                     1.74                4.43
 2    1887          37.58                    −3.45               −8.41
 3    1888          39.39                     1.81                4.82
 4    1889          41.56                     2.17                5.51
 ..    ...            ...                      ...                 ...
 130  2015       17425.03                  −398.04               −2.23
 131  2016       19762.60                  2337.57               13.42
 132  2017       24719.22                  4956.62               25.08
 133  2018       23327.46                −1,391.76               −5.63
 134  2019       28538.44                  5210.98               22.34

 [135 rows x 4 columns],
     0                                                  1
 0 NaN  Wikimedia Commons has media related to Dow Jon...,
    vteComponents of the Dow Jones Industrial Average  \
 0  3M American Express Apple Boeing Caterpillar C...

   vteComponents of the Dow Jones Industrial Average.1
 0  3M American Express Apple Boeing Caterpillar C...   ,
          vteMajor United States stock market indices  \
 0  Dow Jones Industrial Average NYSE Composite NA...

        vteMajor United States stock market indices.1
 0  Dow Jones Industrial Average NYSE Composite NA...  ,
   vteMajor American stock market indices  \
 0                          United States
 1                                 Canada
 2                                 Mexico
 3                               Colombia
 4                                 Brazil
 5                                  Chile
 6                              Argentina
 7                                   Peru

             vteMajor American stock market indices.1
 0  Dow Jones Industrial Average Dow Jones Transpo...
 1                 S&P/TSX 60 S&P/TSX Composite Index
 2                   Indice de Precios y Cotizaciones
 3  COLCAP Indice General de la Bolsa de Valores d...
 4                                     Índice Bovespa
 5             Índice de Precio Selectivo de Acciones
 6                                             MERVAL
 7                         S&P/BVL Peru General Index  ,
                                          vteNews Corp  \
 0                     Sister company: Fox Corporation
 1   vteDow Jones & CompanyNational consumer produc...
 2                              vteDow Jones & Company
 3                          National consumer products
 4                                 Enterprise products
 5   vteHarperCollinsUnited States Avon Caedmon Ecc...
 6                                    vteHarperCollins
 7                                       United States
 8                                      United Kingdom
 9                                           Australia
 10                                          Christian
 11                                             Canada
 12  vteNews Corp AustraliaNewspapersMetropolitan T...
 13                             vteNews Corp Australia
 14                                         Newspapers
 15                                       Metropolitan
 16                                           Regional
 17                                         Queensland
 18                                              Other
 19  vteNews Corp Australia community newspapersNew...
 20        vteNews Corp Australia community newspapers
 21                                    NewsLocal (NSW)
 22                                     Messenger (SA)
 23                                        Quest (Qld)
 24                                           Victoria
 25                                         Television
 26                                          Magazines
 27                                              Other
 28                                     Formerholdings
 29  vteNews UK The Times The Sunday Times The Sun ...
 30                                         vteNews UK
 31  The Times The Sunday Times The Sun The Times L...
 32  Other assets Move New York Post News America M...
 33                                       Other assets
 34         See also 21st Century Fox News Corporation

                                        vteNews Corp.1
 0                     Sister company: Fox Corporation
 1   vteDow Jones & CompanyNational consumer produc...
 2                              vteDow Jones & Company
 3   Barron's Financial News MarketWatch.com The Wa...
 4                Factiva S&P Dow Jones Indices (2.6%)
 5   vteHarperCollinsUnited States Avon Caedmon Ecc...
 6                                    vteHarperCollins
 7   Avon Caedmon Ecco Harper Harper Perennial I Ca...
 8   William Collins, Sons Collins Bartholomew The ...
 9                                   Angus & Robertson
 10  BibleGateway.com Thomas Nelson Women of Faith ...
 11           Harlequin Enterprises Love Inspired Mira
 12  vteNews Corp AustraliaNewspapersMetropolitan T...
 13                             vteNews Corp Australia
 14  Metropolitan The Australian The Daily Telegrap...
 15  The Australian The Daily Telegraph (Sydney) He...
 16  Queensland Balonne Beacon Bowen Independent Th...
 17  Balonne Beacon Bowen Independent The Cairns Po...
 18  The Coffs Coast Advocate The Daily Examiner Ge...
 19  vteNews Corp Australia community newspapersNew...
 20        vteNews Corp Australia community newspapers
 21  Manly Daily North Shore Times Northern Distric...
 22  News Review Leader Standard Eastern Courier Ea...
 23                      South-West News Southern Star
 24                        Leader Community Newspapers
 25  Sky News Live Sky News Extra Sky News Weather ...
 26            Big League GQ Australia Vogue Australia
 27  Brisbane Broncos (69%) Foxtel (65%) HT&E (15%)...
 28  Australian Associated Press (47%) ADS (Adelaid...
 29  vteNews UK The Times The Sunday Times The Sun ...
 30                                         vteNews UK
 31  The Times The Sunday Times The Sun The Times L...
 32  Other assets Move New York Post News America M...
 33  Move New York Post News America Marketing News...
 34         See also 21st Century Fox News Corporation  ,
        vteDow Jones & Company  \
 0  National consumer products
 1         Enterprise products

                             vteDow Jones & Company.1
 0  Barron's Financial News MarketWatch.com The Wa...
 1               Factiva S&P Dow Jones Indices (2.6%)  ,
   vteHarperCollins                                 vteHarperCollins.1
 0    United States  Avon Caedmon Ecco Harper Harper Perennial I Ca...
 1   United Kingdom  William Collins, Sons Collins Bartholomew The ...
 2        Australia                                  Angus & Robertson
 3        Christian  BibleGateway.com Thomas Nelson Women of Faith ...
 4           Canada           Harlequin Enterprises Love Inspired Mira,
                                vteNews Corp Australia  \
 0                                          Newspapers
 1                                        Metropolitan
 2                                            Regional
 3                                          Queensland
 4                                               Other
 5   vteNews Corp Australia community newspapersNew...
 6         vteNews Corp Australia community newspapers
 7                                     NewsLocal (NSW)
 8                                      Messenger (SA)
 9                                         Quest (Qld)
 10                                           Victoria
 11                                         Television
 12                                          Magazines
 13                                              Other
 14                                     Formerholdings

                              vteNews Corp Australia.1
 0   Metropolitan The Australian The Daily Telegrap...
 1   The Australian The Daily Telegraph (Sydney) He...
 2   Queensland Balonne Beacon Bowen Independent Th...
 3   Balonne Beacon Bowen Independent The Cairns Po...
 4   The Coffs Coast Advocate The Daily Examiner Ge...
 5   vteNews Corp Australia community newspapersNew...
 6         vteNews Corp Australia community newspapers
 7   Manly Daily North Shore Times Northern Distric...
 8   News Review Leader Standard Eastern Courier Ea...
 9                       South-West News Southern Star
 10                        Leader Community Newspapers
 11  Sky News Live Sky News Extra Sky News Weather ...
 12            Big League GQ Australia Vogue Australia
 13  Brisbane Broncos (69%) Foxtel (65%) HT&E (15%)...
 14  Australian Associated Press (47%) ADS (Adelaid...  ,
                                                    0  \
 0                                       Metropolitan
 1                                           Regional
 2                                         Queensland
 3                                              Other
 4  vteNews Corp Australia community newspapersNew...
 5        vteNews Corp Australia community newspapers
 6                                    NewsLocal (NSW)
 7                                     Messenger (SA)
 8                                        Quest (Qld)
 9                                           Victoria

                                                    1
 0  The Australian The Daily Telegraph (Sydney) He...
 1  Queensland Balonne Beacon Bowen Independent Th...
 2  Balonne Beacon Bowen Independent The Cairns Po...
 3  The Coffs Coast Advocate The Daily Examiner Ge...
 4  vteNews Corp Australia community newspapersNew...
 5        vteNews Corp Australia community newspapers
 6  Manly Daily North Shore Times Northern Distric...
 7  News Review Leader Standard Eastern Courier Ea...
 8                      South-West News Southern Star
 9                        Leader Community Newspapers  ,
             0                                                  1
 0  Queensland  Balonne Beacon Bowen Independent The Cairns Po...
 1       Other  The Coffs Coast Advocate The Daily Examiner Ge...,
   vteNews Corp Australia community newspapers  \
 0                             NewsLocal (NSW)
 1                              Messenger (SA)
 2                                 Quest (Qld)
 3                                    Victoria

        vteNews Corp Australia community newspapers.1
 0  Manly Daily North Shore Times Northern Distric...
 1  News Review Leader Standard Eastern Courier Ea...
 2                      South-West News Southern Star
 3                        Leader Community Newspapers  ,
                                           vteNews UK  \
 0  The Times The Sunday Times The Sun The Times L...

                                         vteNews UK.1
 0  The Times The Sunday Times The Sun The Times L...  ,
               0                                                  1
 0  Other assets  Move New York Post News America Marketing News...]

In [3]:
const = pd.read_html("https://en.wikipedia.org/wiki/Dow_Jones_Industrial_Average")[1]

In [4]:
const

,Company,Exchange,Symbol,Industry,Date Added,Notes,"Index Weighting (Apr 30, 2020)"
0,3M,NYSE,NYSE: MMM,Conglomerate,1976-08-09,as Minnesota Mining and Manufacturing,4.35%
1,American Express,NYSE,NYSE: AXP,Financial services,1982-08-30,NaN,2.68%
2,Apple Inc.,NASDAQ,AAPL,Information technology,2015-03-19,NaN,8.01%
3,Boeing,NYSE,NYSE: BA,Aerospace and defense,1987-03-12,NaN,3.87%
4,Caterpillar Inc.,NYSE,NYSE: CAT,Construction and Mining,1991-05-06,NaN,3.34%
5,Chevron Corporation,NYSE,NYSE: CVX,Petroleum industry,2008-02-19,also 1930-07-18 to 1999-11-01,2.63%
6,Cisco Systems,NASDAQ,CSCO,Information technology,2009-06-08,NaN,1.21%
7,The Coca-Cola Company,NYSE,NYSE: KO,Food industry,1987-03-12,also 1932-05-26 to 1935-11-20,1.31%
8,Dow Inc.,NYSE,NYSE: DOW,Chemical industry,2019-04-02,NaN,1.04%
9,ExxonMobil,NYSE,NYSE: XOM,Petroleum industry,1928-10-01,as Standard Oil of New Jersey,1.32%
10,Goldman Sachs,NYSE,NYSE: GS,Financial services,2013-09-20,NaN,5.29%
11,The Home Depot,NYSE,NYSE: HD,Retailing,1999-11-01,NaN,6.17%
12,IBM,NYSE,NYSE: IBM,Information technology,1979-06-29,also 1932-05-26 to 1939-03-04,3.58%
13,Intel,NASDAQ,INTC,Information technology,1999-11-01,NaN,1.72%
14,Johnson & Johnson,NYSE,NYSE: JNJ,Pharmaceutical industry,1997-03-17,NaN,4.18%
15,JPMorgan Chase,NYSE,NYSE: JPM,Financial services,1991-05-06,NaN,2.72%
16,McDonald's,NYSE,NYSE: MCD,Food industry,1985-10-30,NaN,5.23%
17,Merck & Co.,NYSE,NYSE: MRK,Pharmaceutical industry,1979-06-29,NaN,2.25%
18,Microsoft,NASDAQ,MSFT,Information technology,1999-11-01,NaN,4.94%
19,Nike,NYSE,NYSE: NKE,Apparel,2013-09-20,NaN,2.45%
20,Pfizer,NYSE,NYSE: PFE,Pharmaceutical industry,2004-04-08,NaN,1.06%
21,Procter & Gamble,NYSE,NYSE: PG,Fast-moving consumer goods,1932-05-26,NaN,3.26%
22,Raytheon Technologies,NYSE,NYSE: RTX,Aerospace and defense,1939-03-14,"as United Aircraft, later transformed into Uni...",1.89%
23,The Travelers Companies,NYSE,NYSE: TRV,Financial services,2009-06-08,NaN,2.95%
24,UnitedHealth Group,NYSE,NYSE: UNH,Managed health care,2012-09-24,NaN,8.01%
25,Verizon,NYSE,NYSE: VZ,Telecommunication,2004-04-08,NaN,1.62%
26,Visa Inc.,NYSE,NYSE: V,Financial services,2013-09-20,NaN,5.06%
27,Walmart,NYSE,NYSE: WMT,Retailing,1997-03-17,NaN,3.44%
28,Walgreens Boots Alliance,NASDAQ,WBA,Retailing,2018-06-26,NaN,1.26%
29,The Walt Disney Company,NYSE,NYSE: DIS,Broadcasting and entertainment,1991-05-06,NaN,3.12%

In [5]:
const = const.iloc[:, :5].copy()
const

,Company,Exchange,Symbol,Industry,Date Added
0,3M,NYSE,NYSE: MMM,Conglomerate,1976-08-09
1,American Express,NYSE,NYSE: AXP,Financial services,1982-08-30
2,Apple Inc.,NASDAQ,AAPL,Information technology,2015-03-19
3,Boeing,NYSE,NYSE: BA,Aerospace and defense,1987-03-12
4,Caterpillar Inc.,NYSE,NYSE: CAT,Construction and Mining,1991-05-06
5,Chevron Corporation,NYSE,NYSE: CVX,Petroleum industry,2008-02-19
6,Cisco Systems,NASDAQ,CSCO,Information technology,2009-06-08
7,The Coca-Cola Company,NYSE,NYSE: KO,Food industry,1987-03-12
8,Dow Inc.,NYSE,NYSE: DOW,Chemical industry,2019-04-02
9,ExxonMobil,NYSE,NYSE: XOM,Petroleum industry,1928-10-01
10,Goldman Sachs,NYSE,NYSE: GS,Financial services,2013-09-20
11,The Home Depot,NYSE,NYSE: HD,Retailing,1999-11-01
12,IBM,NYSE,NYSE: IBM,Information technology,1979-06-29
13,Intel,NASDAQ,INTC,Information technology,1999-11-01
14,Johnson & Johnson,NYSE,NYSE: JNJ,Pharmaceutical industry,1997-03-17
15,JPMorgan Chase,NYSE,NYSE: JPM,Financial services,1991-05-06
16,McDonald's,NYSE,NYSE: MCD,Food industry,1985-10-30
17,Merck & Co.,NYSE,NYSE: MRK,Pharmaceutical industry,1979-06-29
18,Microsoft,NASDAQ,MSFT,Information technology,1999-11-01
19,Nike,NYSE,NYSE: NKE,Apparel,2013-09-20
20,Pfizer,NYSE,NYSE: PFE,Pharmaceutical industry,2004-04-08
21,Procter & Gamble,NYSE,NYSE: PG,Fast-moving consumer goods,1932-05-26
22,Raytheon Technologies,NYSE,NYSE: RTX,Aerospace and defense,1939-03-14
23,The Travelers Companies,NYSE,NYSE: TRV,Financial services,2009-06-08
24,UnitedHealth Group,NYSE,NYSE: UNH,Managed health care,2012-09-24
25,Verizon,NYSE,NYSE: VZ,Telecommunication,2004-04-08
26,Visa Inc.,NYSE,NYSE: V,Financial services,2013-09-20
27,Walmart,NYSE,NYSE: WMT,Retailing,1997-03-17
28,Walgreens Boots Alliance,NASDAQ,WBA,Retailing,2018-06-26
29,The Walt Disney Company,NYSE,NYSE: DIS,Broadcasting and entertainment,1991-05-06

In [6]:
const.rename(columns = {"Date Added":"Date_Added"}, inplace = True)

In [9]:
const.Date_Added = pd.to_datetime(const.Date_Added)

In [10]:
const.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Company     30 non-null     object
 1   Exchange    30 non-null     object
 2   Symbol      30 non-null     object
 3   Industry    30 non-null     object
 4   Date_Added  30 non-null     datetime64[ns]
dtypes: datetime64[ns](1), object(4)
memory usage: 1.3+ KB

## Normalizing Unicode Strings and Getting the Ticker Symbols

In [ ]:
import unicodedata

In [ ]:
const.Symbol

In [ ]:
const.Symbol.to_list()

In [ ]:
const.info()

In [ ]:
const.Symbol.apply(lambda x: unicodedata.normalize("NFKD", x))

In [ ]:
const.Symbol = const.Symbol.apply(lambda x: unicodedata.normalize("NFKD", x))

In [ ]:
const.Symbol[0]

In [ ]:
const["Ticker"] = const.Symbol.str.split(": ").apply(lambda x: x[-1])

In [ ]:
const

In [ ]:
ticker_list = const.Ticker.to_list()

In [ ]:
ticker_list

In [ ]:
const.to_csv("const.csv", index = False)

## Loading and Saving Historical Stock Prices

In [ ]:
import pandas as pd
import yfinance as yf

In [ ]:
ticker_list

In [ ]:
prices = yf.download(ticker_list, start = "2007-01-01", end = "2020-03-31")

In [ ]:
prices

In [ ]:
prices.info()

In [ ]:
prices = prices.loc[:,"Close"].copy()

In [ ]:
prices.info()

In [ ]:
prices

In [ ]:
prices.to_csv("const_prices.csv")

In [ ]:
dji = yf.download("^DJI", start = "2007-01-01",  end = "2020-03-31")

In [ ]:
dji

In [ ]:
dji.to_csv("dji.csv")